name: CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew runBuild --no-daemon
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          build/dist/cv.to.pdf-2.0.0-SNAPSHOT.zip
          build/out/cv.pdf
          build/out/cover_letter.pdf
